openapi: 3.0.3
info:
  title: ScratchNow API
  description: ScratchNow API Swagger Document
  version: 1.0.0

externalDocs:
  description: Github Respository
  url: https://github.com/codestates/ScratchNow

servers:
  - url: https://localhost:3300

tags:
  - name: user
    description: 사용자 계정 API
  - name: post
    description: 게시물 API
  - name: feed
    description: 피드 API
  - name: comment
    description: 댓글 API
  - name: like
    description: 좋아요 API

paths:
  /user:
    post:
      tags:
        - user
      summary: 회원가입
      description: 서비스 자체 회원가입(이메일)
      requestBody:
        description: 회원정보 생성
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Signup'
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignupRes'
    get:
      tags:
        - user
      summary: 사용자 정보 조회
      responses:
    patch:
      tags:
        - user
      summary: 회원정보 수정(프로필 이미지, 닉네임, 상태메시지)
      responses:
    delete:
      tags:
        - user
      summary: 회원탈퇴
      responses:
  /user/login:
    post:
      tags:
        - user
      summary: 이메일 로그인(JWT)
      description: email login
      operationId: loginUser
      requestBody:
        description: 이메일 로그인
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
  /user/logout:
    get:
      tags:
        - user
      summary: 로그아웃
      description: 쿠키 삭제
      operationId: logoutUser
      responses:
        default:
          description: successful operation
  /user/emailcheck:
    post:
      tags:
        - user
      summary: 이메일 인증번호 발송
      description: 이메일 인증번호 메일 발송
      operationId: deleteUser
      requestBody:
        description: 이메일 인증 요청
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailAuthentication'
      responses:
  /user/kakao/login:
    post:
      tags:
        - user
      summary: 카카오 소셜로그인
      description: Kakao OAuth
      operationId: ?
      requestBody:
        description: 카카오 소셜로그인
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Kakao'
      responses:
  /user/google/login:
    post:
      tags:
        - user
      summary: Update user
      description: This can only be done by the logged in user.
      operationId: updateUser
      requestBody:
        description: 구글 소셜로그인
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Google'
      responses:
  /user/profileimagenull:
    patch:
      tags:
        - user
      summary: 프로필 이미지 기본으로 변경
      responses:
  /user/nicknamecheck:
    get:
      tags:
        - user
      summary: 닉네임 중복 여부 확인
      responses:
  /user/password:
    patch:
      tags:
        - user
      summary: 비밀번호 수정
      responses:
  /post:
    post:
      tags:
        - post
      summary: 게시물 등록
      responses:
    get:
      tags:
        - post
      summary: 게시물 조회
      responses:
    patch:
      tags:
        - post
      summary: 게시물 수정
      responses:
    delete:
      tags:
        - post
      summary: 게시물 삭제
      responses:
  /feed/data:
    get:
      tags:
        - feed
      summary: 최신순 피드 조회
      responses:
  /feed/likes:
    get:
      tags:
        - feed
      summary: 인기순 피드 조회
      responses:
  /feed/user:
    get:
      tags:
        - feed
      summary: 유저 피드 조회
      responses:
  /comment:
    post:
      tags:
        - comment
      summary: 댓글 등록
      responses:
    get:
      tags:
        - comment
      summary: 댓글 조회
      responses:
    patch:
      tags:
        - comment
      summary: 댓글 수정
      responses:
    delete:
      tags:
        - comment
      summary: 댓글 삭제
      responses:
  /like:
    post:
      tags:
        - like
      summary: 좋아요 추가 또는 취소
      responses:

components:
  schemas:
    Signup:
      type: object
      properties:
        email:
          type: string
          example: scratch2022@gmail.com
        password:
          type: string
          example: 'test'
        nickname:
          type: string
          example: 'scratchnow'
    SignupRes:
      type: object
      properties:
        id:
          type: number
        email:
          type: string
          # example: scratch2022@gmail.com
        password:
          type: string
          # example: 'test'
        nickname:
          type: string
          # example: 'scratchnow'